### PR TITLE
Update Project.ipynb

### PR DESCRIPTION
**Pull request by larasacerqueira**

### CODE REVIEW

**Comment by larasacerqueira** [comment]
I added the XGBoost

**Comment by HvdB01** [comment]
@larasacerqueira I think you made a mistake in the pull request. Because I don't see the XGBoost. I only see an empty file.

**Comment by larasacerqueira** [comment]
I know I am having troubles with making pull requests for some reason 🤷‍♀️

Enviado a partir do Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Hidde ***@***.***>
Enviado: Saturday, February 17, 2024 9:37:06 PM
Para: Berga20/DS-Project-Group4 ***@***.***>
Cc: Lara Carneiro De Sa Cerqueira ***@***.***>; Mention ***@***.***>
Assunto: Re: [Berga20/DS-Project-Group4] Update Project.ipynb (PR #24)


@larasacerqueira<https://github.com/larasacerqueira> I think you made a mistake in the pull request. Because I don't see the XGBoost. I only see an empty file.

**Comment by HvdB01** [comment]
Schermafbeelding 2024-02-17 213751

**Comment by HvdB01** [comment]
@larasacerqueira 
If you need any help, shout

**Pull request closed without merging**
